### ISSUE TITLE
No Aug data

### ISSUE THREAD

**Issue by sabrinaluo** [ywng/mpf.portal#1]
Hi ywng, I visit your MPF frequently, but I find there is no data from August.
Could you check whether there is a problem or something? thank you. Your site for MPF is really helpful for me XD

**Comment by ywng** [comment]
As you may know that MPF fund unit price is not updated as fast as stocks. It may take more than 3-4 working days time lag. (how recent the unit price depends on Bloomberg, not my program)

I have checked that the program should work fine, and the unit price [last updated date] on Bloomberg is just up to 31st June too

**Comment by ywng** [comment]
And, there is one bad practise in my code...
I just take the date of the first fund as the latest date, and apply across all funds.
so, even other funds has more updated data. It is not shown.
[but the json data getting via api call is correct]

**Comment by sabrinaluo** [comment]
Thanks for your reply.
I think the price should be fluctuating from April to July, is it also because of the problem you mentioned above?

**Comment by ywng** [comment]
YES,  the price should be fluctuating from April to July.
The data is missing for that period because there was a downtime / issue in the released environment. And, I didn't have time to fix it. That's why the extractor didnt work and no data in that period is extracted into my db.

for the fund price in the past year, we can actually download from this (excel format: https://bank.hangseng.com/1/2/e-services/e-mpf/fund-price-performance/price#01).
